name: build

on:
  push:
    tags:
      - "build_*"

env:
  BUILDROOT_VERSION: 2019.11.1
  GDB_VERSION: 8.3.1

jobs:
  build-all: 
    runs-on: ubuntu-18.04
    strategy:
      matrix: 
        TARGET_ARCH: [arm, armeb, aarch64, aarch64_be, mips, mips1, mipsr6, mipsel, mips1el, mipsr6el, mips64, mips64r6, mips64el, mips64r6el, powerpc, powerpc64, powerpc64le, riscv64, i586, x86_64]
    env:
      M: ${{ matrix.TARGET_ARCH }}-linux
      TARGET_ARCH: ${{ matrix.TARGET_ARCH }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: src
    - name: setup
      run: |
       mkdir ${TARGET_ARCH}
       sudo apt-get install texinfo
    - name: run special selector
      run: |
        source src/scripts/selector.sh
    - name: build toolchain
      run: |
        bash src/scripts/buildroot.sh
    - name: build shell
      run: |
        bash src/scripts/shell.sh
    - name: build busybox
      run: |
        bash src/scripts/busybox.sh
    - name: build dropbear
      run: |
        bash src/scripts/dropbear.sh
    - name: build socat
      run: |
        bash src/scripts/build_static.sh socat
    - name: build lsof
      run: |
        bash src/scripts/build_static.sh lsof
    - name: build strace
      run: |
        bash src/scripts/build_static.sh strace
    - name: build tcpdump
      run: |
        bash src/scripts/build_static.sh tcpdump
    - name: build gdb
      run: |
        bash src/scripts/gdb.sh
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.TARGET_ARCH}}_tools
        path: ${{ matrix.TARGET_ARCH}}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.TARGET_ARCH}}_sdk-buildroot.tar.gz
        path: ${{ matrix.TARGET_ARCH}}_sdk-buildroot.tar.gz


  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{github.actor}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_REPOSITORY: ${{github.repository}}
    needs: [build-all]
    steps:
    - name: setup
      run: |
        mkdir allinone
    - uses: actions/download-artifact@v3
      with:
        path: allinone/
    - name: zip files
      run: |
        mkdir zipfiles
        mv allinone/*_sdk-buildroot.tar.gz/* zipfiles/
        rm -r allinone/*_sdk-buildroot.tar.gz
        cd allinone
        ls .|xargs -i{} zip -r ../zipfiles/{}.zip {}
        cd ..
        zip -r zipfiles/allinone.zip allinone
    - name: show files
      run: |
        ls -al .
        tree .
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          zipfiles/*